import { createRoute, OpenAPIHono } from "@hono/zod-openapi";
import type { Bindings } from "../env";
import { ErrorResponseSchema } from "../schemas/common";
import { ApprovalDecisionRequestSchema } from "../schemas/approval";
import {
	DeleteQuotationQuerySchema,
	ListQuotationsQuerySchema,
	ListQuotationsResponseSchema,
	PdfProxyResponseSchema,
	QuotationDataResponseSchema,
	QuotationIdParamSchema,
} from "../schemas/quotation";
import {
	createPdfService,
	createQuotationService,
	handleServiceError,
} from "./utils";

const listQuotationsRoute = createRoute({
	method: "get",
	path: "/quotations",
	tags: ["Quotation"],
	summary: "List quotations with pagination, sorting, and filters",
	request: {
		query: ListQuotationsQuerySchema,
	},
	responses: {
		200: {
			content: {
				"application/json": {
					schema: ListQuotationsResponseSchema,
				},
			},
			description: "Paginated quotation list",
		},
		400: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Validation error",
		},
	},
});

const getQuotationRoute = createRoute({
	method: "get",
	path: "/quotations/{id}",
	tags: ["Quotation"],
	summary: "Retrieve a quotation by ID",
	request: {
		params: QuotationIdParamSchema,
	},
	responses: {
		200: {
			content: {
				"application/json": {
					schema: QuotationDataResponseSchema,
				},
			},
			description: "Quotation retrieved",
		},
		404: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Quotation not found",
		},
	},
});

const deleteQuotationRoute = createRoute({
	method: "delete",
	path: "/quotations/{id}",
	tags: ["Quotation"],
	summary: "Soft-delete a quotation",
	request: {
		params: QuotationIdParamSchema,
		query: DeleteQuotationQuerySchema,
	},
	responses: {
		200: {
			content: {
				"application/json": {
					schema: QuotationDataResponseSchema,
				},
			},
			description: "Quotation soft-deleted",
		},
		404: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Quotation not found",
		},
	},
});

const approveQuotationRoute = createRoute({
	method: "post",
	path: "/quotations/{id}/approve",
	tags: ["Quotation"],
	summary: "Approve a quotation",
	request: {
		params: QuotationIdParamSchema,
		body: {
			content: {
				"application/json": {
					schema: ApprovalDecisionRequestSchema,
				},
			},
		},
	},
	responses: {
		200: {
			content: {
				"application/json": {
					schema: QuotationDataResponseSchema,
				},
			},
			description: "Quotation approved",
		},
		400: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Validation error",
		},
		403: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Quotation is not pending approval",
		},
		404: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Quotation or approval step not found",
		},
		409: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Approval step already decided",
		},
	},
});

const rejectQuotationRoute = createRoute({
	method: "post",
	path: "/quotations/{id}/reject",
	tags: ["Quotation"],
	summary: "Reject a quotation",
	request: {
		params: QuotationIdParamSchema,
		body: {
			content: {
				"application/json": {
					schema: ApprovalDecisionRequestSchema,
				},
			},
		},
	},
	responses: {
		200: {
			content: {
				"application/json": {
					schema: QuotationDataResponseSchema,
				},
			},
			description: "Quotation rejected",
		},
		400: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Validation error",
		},
		403: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Quotation is not pending approval",
		},
		404: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Quotation or approval step not found",
		},
		409: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Approval step already decided",
		},
	},
});

const generatePdfRoute = createRoute({
	method: "post",
	path: "/quotations/{id}/pdf/generate",
	tags: ["Quotation"],
	summary: "Generate a quotation PDF via external service",
	request: {
		params: QuotationIdParamSchema,
	},
	responses: {
		200: {
			content: {
				"application/json": {
					schema: PdfProxyResponseSchema,
				},
			},
			description: "PDF generated by external service",
		},
		404: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Quotation not found",
		},
		502: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "External PDF service error",
		},
	},
});

const downloadPdfRoute = createRoute({
	method: "get",
	path: "/quotations/{id}/pdf/download",
	tags: ["Quotation"],
	summary: "Download a quotation PDF via external service",
	request: {
		params: QuotationIdParamSchema,
	},
	responses: {
		200: {
			content: {
				"application/json": {
					schema: PdfProxyResponseSchema,
				},
			},
			description: "PDF download response from external service",
		},
		404: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "Quotation not found",
		},
		502: {
			content: {
				"application/json": {
					schema: ErrorResponseSchema,
				},
			},
			description: "External PDF service error",
		},
	},
});

export const quotationRoutes = new OpenAPIHono<{ Bindings: Bindings }>();

quotationRoutes.openapi(listQuotationsRoute, async (c) => {
	try {
		const query = c.req.valid("query");
		const result = await createQuotationService(c.env.DB).listQuotations(query);
		return c.json({ success: true as const, data: result }, 200);
	} catch (error) {
		return handleServiceError(c, error);
	}
});

quotationRoutes.openapi(getQuotationRoute, async (c) => {
	try {
		const { id } = c.req.valid("param");
		const quotation = await createQuotationService(c.env.DB).getQuotation(id);
		return c.json({ success: true as const, data: quotation }, 200);
	} catch (error) {
		return handleServiceError(c, error);
	}
});

quotationRoutes.openapi(deleteQuotationRoute, async (c) => {
	try {
		const { id } = c.req.valid("param");
		const { deletedBy } = c.req.valid("query");
		const quotation =
			await createQuotationService(c.env.DB).deleteQuotation(id, deletedBy);
		return c.json({ success: true as const, data: quotation }, 200);
	} catch (error) {
		return handleServiceError(c, error);
	}
});

quotationRoutes.openapi(approveQuotationRoute, async (c) => {
	try {
		const { id } = c.req.valid("param");
		const body = c.req.valid("json");
		const quotation =
			await createQuotationService(c.env.DB).approveQuotation(id, body);
		return c.json({ success: true as const, data: quotation }, 200);
	} catch (error) {
		return handleServiceError(c, error);
	}
});

quotationRoutes.openapi(rejectQuotationRoute, async (c) => {
	try {
		const { id } = c.req.valid("param");
		const body = c.req.valid("json");
		const quotation =
			await createQuotationService(c.env.DB).rejectQuotation(id, body);
		return c.json({ success: true as const, data: quotation }, 200);
	} catch (error) {
		return handleServiceError(c, error);
	}
});

quotationRoutes.openapi(generatePdfRoute, async (c) => {
	try {
		const { id } = c.req.valid("param");
		const quotation = await createQuotationService(c.env.DB).getQuotation(id);
		const result = await createPdfService(c.env.PDF_SERVICE_URL).generate(
			quotation,
		);
		return c.json({ success: true as const, data: result }, 200);
	} catch (error) {
		return handleServiceError(c, error);
	}
});

quotationRoutes.openapi(downloadPdfRoute, async (c) => {
	try {
		const { id } = c.req.valid("param");
		const quotation = await createQuotationService(c.env.DB).getQuotation(id);
		const result = await createPdfService(c.env.PDF_SERVICE_URL).download(
			quotation,
		);
		return c.json({ success: true as const, data: result }, 200);
	} catch (error) {
		return handleServiceError(c, error);
	}
});
